version: "3"
services:
  api-test:
    image: node:lts-alpine
    container_name: LibQualityTests 
    working_dir: /home/app
    volumes:
      - .:/home/app
    depends_on:
      - mongo 
    networks:
      - LibQuality 
    command: npm run test:docker 
  mongo:
    image: mongo 
    container_name: LibQualityDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: verySecretPassword
    command: mongod
    networks:
      - LibQuality

volumes:
  mongo-volume:

networks:
  LibQuality:
    driver: bridge



